---

# ==================================
# DHCP LEASE CONFIGURATION
# ==================================

# --------------------------
# GET CURRENT DHCP LEASES
# --------------------------
# Menyimpan daftar DHCP Lease yang saat ini aktif pada MikroTik.

- name: Get current DHCP leases
  community.routeros.command:
    commands:
      - /ip dhcp-server lease print detail without-paging
  register: current_lease
  changed_when: false

# ---------------------------------------
# REMOVE DYNAMIC LEASE FOR MANAGED MAC
# ---------------------------------------
# Menghapus Dynamic Lease pada MAC yang dikelola sebelum menerapkan Static Lease.

- name: Remove dynamic lease for managed MAC
  community.routeros.command:
    commands:
      - >
        :local leaseMAC "{{ item.mac_address }}";

        :if ([:len [/ip dhcp-server lease find
        mac-address=$leaseMAC dynamic=yes]] > 0) do={

          /ip dhcp-server lease remove
          [/ip dhcp-server lease find
          mac-address=$leaseMAC dynamic=yes];

        }
  loop: "{{ mikrotik_dhcp_lease }}"
  loop_control:
    label: "{{ item.comment }}"

# ---------------------------
# ADD OR UPDATE DHCP LEASE
# ---------------------------
# Menambahkan DHCP Lease baru atau memperbarui alamat IP,
# DHCP Server, dan komentar berdasarkan MAC Address perangkat.

- name: Add or Update DHCP lease
  community.routeros.command:
    commands:
      - >
        # Menyimpan parameter DHCP Lease dari konfigurasi.
        :local leaseIP "{{ item.ip_address }}";
        :local leaseMAC "{{ item.mac_address }}";
        :local leaseComment "{{ item.comment }}";
        :local leaseServer "{{ item.dhcp_server }}";

        # Memeriksa apakah DHCP Lease dengan MAC Address tersebut sudah ada.
        :if ([:len [/ip dhcp-server lease find mac-address=$leaseMAC]] = 0) do={

          # Menambahkan DHCP Lease baru jika belum ditemukan
          /ip dhcp-server lease add \
          address=$leaseIP \
          mac-address=$leaseMAC \
          server=$leaseServer \
          comment=$leaseComment;

        } else={

          # Memperbarui DHCP Lease jika parameter konfigurasi berbeda.
          :if (
            [/ip dhcp-server lease get [find mac-address=$leaseMAC] address] != $leaseIP
            or
            [/ip dhcp-server lease get [find mac-address=$leaseMAC] comment] != $leaseComment
            or
            [/ip dhcp-server lease get [find mac-address=$leaseMAC] server] != $leaseServer
          ) do={
            # Menerapkan konfigurasi terbaru pada DHCP Lease yang sudah ada.
            /ip dhcp-server lease set \
            [find mac-address=$leaseMAC] \
            address=$leaseIP \
            server=$leaseServer \
            comment=$leaseComment;

          }

        }
  loop: "{{ mikrotik_dhcp_lease }}"
  loop_control:
    label: "{{ item.comment }}"
