---

- name: Include DHCP network tasks
  import_tasks: network.yml

- name: Include DHCP pool tasks
  import_tasks: pool.yml

- name: Include DHCP server tasks
  import_tasks: server.yml

- name: Include DHCP lease tasks
  import_tasks: lease.yml
