---

# =============================
# DHCP NETWORK CONFIGURATION
# =============================

# ----------------------------
# GET CURRENT DHCP NETWORKS
# ----------------------------
# Mengambil konfigurasi DHCP Network saat ini sebagai kondisi aktual MikroTik.

- name: Get current DHCP networks
  community.routeros.command:
    commands:
      - /ip dhcp-server network print detail without-paging
  register: dhcp_network_all
  changed_when: false

# Menyusun daftar DHCP Network yang saat ini terdapat pada MikroTik.
- name: Build existing network list
  set_fact:
    existing_networks: >-
      {{
        dhcp_network_all.stdout[0]
        | regex_findall('address=([0-9./]+)')
      }}

# Menyusun daftar DHCP Network yang diinginkan berdasarkan inventory.
- name: Build desired DHCP network list
  set_fact:
    desired_networks: "{{ mikrotik_dhcp | map(attribute='dhcp_network') | list }}"

# ------------------------------
# REMOVE UNUSED DHCP NETWORKS
# ------------------------------
# Menghapus DHCP Network yang tidak lagi terdapat dalam konfigurasi inventory.

- name: Remove unused DHCP networks
  community.routeros.command:
    commands:
      - /ip dhcp-server network remove [find where address="{{ item }}"]
  loop: "{{ existing_networks | difference(desired_networks) }}"
  loop_control:
    label: "{{ item }}"

# ----------------------
# UPDATE DHCP NETWORK 
# ----------------------
# Memperbarui gateway atau DNS Server apabila konfigurasi DHCP Network berbeda.

- name: Update DHCP network
  community.routeros.command:
    commands:
      - >
        /ip dhcp-server network set
        [find where address="{{ item.dhcp_network }}"]
        gateway={{ item.dhcp_gateway }}
        dns-server={{ item.dns_server }}
  when: >
    (
      dhcp_network_all.stdout[0] is search("address=" ~ item.dhcp_network)
    ) and (
      (
        dhcp_network_all.stdout[0] is not search("address=" ~ item.dhcp_network ~ ".*gateway=" ~ item.dhcp_gateway)
      )
      or
      (
        dhcp_network_all.stdout[0] is not search("address=" ~ item.dhcp_network ~ ".*dns-server=" ~ item.dns_server)
      )
    )
  loop: "{{ mikrotik_dhcp }}"
  loop_control:
    label: "{{ item.dhcp_network }}"

# -------------------
# ADD DHCP NETWORK  
# -------------------
# Menambahkan DHCP Network jika subnet belum terdapat pada MikroTik.

- name: Add DHCP network
  community.routeros.command:
    commands:
      - >
        /ip dhcp-server network add
        address={{ item.dhcp_network }}
        gateway={{ item.dhcp_gateway }}
        dns-server={{ item.dns_server }}
  when: item.dhcp_network not in existing_networks
  loop: "{{ mikrotik_dhcp }}"
  loop_control:
    label: "{{ item.dhcp_network }}"
