mikrotik_interfaces:

  - interface: wlan1
    dhcp: true

  - interface: ether2
    ip_address: 172.16.10.1/24



mikrotik_dhcp:

  - interface: ether2
    dhcp_name: dhcp_apis
    dhcp_pool: KARL
    dhcp_range: 172.16.10.6-172.16.10.10
    dhcp_network: 172.16.10.0/24
    dhcp_gateway: 172.16.10.1
    dns_server: 8.8.8.8



mikrotik_nat:
  - chain: srcnat
    out_interface: wlan1
    action: masquerade



mikrotik_dns:
  servers:
    - 8.8.8.8
    - 4.4.4.4
  allow_remote_requests: yes
