mikrotik_interfaces:

  - interface: wlan1
    dhcp: true

  - interface: ether2
    ip_address: 172.222.10.1/24

  - interface: ether3
    ip_address: 192.12.11.1/24


mikrotik_dhcp:

  - interface: ether2
    dhcp_name: dhcp_cek
    dhcp_pool: dhcp_Raspi
    dhcp_range: 172.222.10.12-172.222.10.22
    dhcp_network: 172.222.10.0/24
    dhcp_gateway: 172.222.10.1
    dns_server: 8.8.8.8



mikrotik_dhcp_lease:
  - ip_address: 172.222.10.21
    mac_address: DC:A6:32:E6:13:02
    comment: Raspberry_ether2



mikrotik_nat:
  - chain: srcnat
    out_interface: wlan1
    action: masquerade

  - chain: dstnat
    protocol: tcp
    dst_port: 5900
    to_address: 172.222.10.21
    to_port: 5900
    action: dst-nat

  - chain: dstnat
    protocol: tcp
    dst_port: 8080
    to_address: 172.222.10.21
    to_port: 8080
    action: dst-nat



mikrotik_dns:
  servers:
    - 8.8.8.8
  allow_remote_requests: yes
