# ====================================================
# Router Configuration
# ====================================================
# File ini berisi konfigurasi yang akan diterapkan
# pada perangkat.

# -----------------------------------------------
# Interface Configuration
# -----------------------------------------------
# Konfigurasi alamat IP dan interface jaringan.

mikrotik_interfaces:

  - interface: wlan1
    dhcp: true

  - interface: ether2
    ip_address: 10.10.10.1/24


# -------------------------------------
# DHCP Configuration
# -------------------------------------
# Parameter konfigurasi DHCP Server.

mikrotik_dhcp:

  - interface: ether2
    dhcp_name: dhcp_IoT
    dhcp_pool: dhcp_RaspberryPi
    dhcp_range: 10.10.10.5-10.10.10.10
    dhcp_network: 10.10.10.0/24
    dhcp_gateway: 10.10.10.1
    dns_server: 8.8.8.8


# ---------------------------------
# DHCP Lease
# ---------------------------------
# Konfigurasi static DHCP lease.

mikrotik_dhcp_lease:
  - ip_address: 10.10.10.9
    mac_address: DC:A6:32:E6:13:02
    dhcp_server: dhcp_IoT
    comment: Raspberry1

  - ip_address: 10.10.10.6
    mac_address: 2C:3A:E8:27:92:95
    dhcp_server: dhcp_IoT
    comment: ESP1


# ---------------------------------------
# Firewall NAT
# ---------------------------------------
# Konfigurasi aturan NAT pada MikroTik.

mikrotik_nat:
  - chain: srcnat
    out_interface: wlan1
    action: masquerade

  - chain: dstnat
    in_interface: wlan1
    protocol: tcp
    dst_port: 5900
    to_address: 10.10.10.9
    to_port: 5900
    action: dst-nat

  - chain: dstnat
    in_interface: wlan1
    protocol: tcp
    dst_port: 8080
    to_address: 10.10.10.9
    to_port: 8000
    action: dst-nat


# -------------------------
# DNS Configuration
# -------------------------
# Konfigurasi DNS Server.

mikrotik_dns:
  servers:
    - 8.8.8.8
    - 4.4.4.4
  allow_remote_requests: yes

mikrotik_dns_static:
    - name: edge.iot
      address: 10.10.10.9
