---
# =======================
# BACKUP CONFIGURATION
# =======================

# -----------------------------
# GENERATE BACKUP IDENTIFIER
# -----------------------------

- name: Create timestamp
# Membuat timestamp sebagai identitas unik untuk file backup.
  set_fact:
    backup_time: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

- name: Set backup filename
# Menyusun nama file backup berdasarkan hostname dan timestamp.
  set_fact:
    backup_name: "{{ inventory_hostname }}-{{ backup_time }}"

# ---------------------------------
# PREPARE LOCAL BACKUP DIRECTORY
# ---------------------------------

- name: Ensure local backup directory exists
# Membuat direktori backup pada CI/CD Controller apabila belum tersedia.
  delegate_to: localhost
  file:
    path: "{{ playbook_dir }}/../backups"
    state: directory
    mode: '0755'

# -----------------------------------
# CREATE BACKUP ON MIKROTIK DEVICE
# -----------------------------------

- name: Create router backup
  community.routeros.command:
# Membuat file backup biner pada perangkat MikroTik.
    commands:
      - "/system backup save name={{ backup_name }}"

# -----------------------------------------
# WAIT FOR ROUTER TO FINISH WRITING FILE
# -----------------------------------------

- name: Wait for file creation
  pause:
    seconds: 3

# -----------------------------------
# DOWNLOAD BACKUP FILE FROM ROUTER
# -----------------------------------

- name: Download binary backup
  ansible.netcommon.net_get:
# Mengunduh file backup dari MikroTik ke direktori backup pada CI/CD COntroller.
    src: "{{ backup_name }}.backup"
    dest: "{{ playbook_dir }}/../backups/{{ backup_name }}.backup"

  register: download_result
  retries: 3
  delay: 3
  until: download_result is succeeded

# ------------------------------------
# VERIFY BACKUP FILE EXISTS LOCALLY
# ------------------------------------

- name: Verify backup file exists
  delegate_to: localhost
# Memastikan file backup berhasil tersimpan pada CI/CD Controller.
  stat:
    path: "{{ playbook_dir }}/../backups/{{ backup_name }}.backup"

  register: backup_file

- name: Validate backup success
# Memvalidasi keberhasilan proses backup.
  assert:
    that:
      - backup_file.stat.exists
    fail_msg: >
      [BACKUP FAILED]
      Backup file was not created successfully.
    success_msg: >
      [BACKUP SUCCESS]
      Backup file created successfully.

# -------------------
# BACKUP COMPLETED
# -------------------

- name: Display backup success message
  debug:
    msg: >
      [BACKUP SUCCESS]
      {{ backup_name }}.backup downloaded successfully.
