---

- name: Create timestamp
  set_fact:
    backup_time: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Set backup filename
  set_fact:
    backup_name: "{{ inventory_hostname }}-{{ backup_time }}"


- name: Ensure backup directory exists
  delegate_to: localhost
  file:
    path: "{{ playbook_dir }}/../backups"
    state: directory
    mode: '0755'


- name: Create binary backup
  community.routeros.command:
    commands:
      - /system backup save name={{ backup_name }}

- name: Wait for file creation
  pause:
    seconds: 5


- name: Download binary backup
  ansible.netcommon.net_get:
    src: "{{ backup_name }}.backup"
    dest: "{{ playbook_dir }}/../backups/{{ backup_name }}.backup"


- name: Backup completed
  debug:
    msg: "[BACKUP SUCCESS] Binary snapshot saved as {{ backup_name }}.backup"
