---
# =================================
# Verify MikroTik Configuration
# =================================
# Playbook untuk menjalankan proses verifikasi setelah
# deployment selesai.

- name: Verify MikroTik Configuration

  hosts: mikrotik

  gather_facts: no


  roles:

    - verify
