---
# ====================
# DNS CONFIGURATION
# ====================

# --------------------------------
# GET CURRENT DNS CONFIGURATION
# --------------------------------

- name: Get current DNS configuration
  community.routeros.command:
    commands:
      - /ip dns print detail without-paging
# Menyimpan konfigurasi DNS yang sedang aktif pada MikroTik.
  register: current_dns
  changed_when: false

# ---------------------------
# UPDATE DNS cONFIGURATION
# ---------------------------

- name: Update DNS configuration
  community.routeros.command:
    commands:
      - >
        /ip dns set
        servers={{ mikrotik_dns.servers | join(',') }}
        allow-remote-requests={{ 'yes' if mikrotik_dns.allow_remote_requests else 'no' }}
# Memperbarui DNS Server atau allow-remote-requests apabila konfigurasi berbeda dengan inventory.
  when: >
    (
      (current_dns.stdout[0] | replace(' ', ''))
      is not search("servers=" ~ (mikrotik_dns.servers | join(',')))
    )
    or
    (
      (current_dns.stdout[0] | replace(' ', ''))
      is not search("allow-remote-requests=" ~ ('yes' if mikrotik_dns.allow_remote_requests else 'no'))
    )
