---

- name: Verify IP
  community.routeros.command:
    commands:
      - /ip address print
  register: ip


- debug:
    var: ip.stdout_lines


- name: Verify DHCP
  community.routeros.command:
    commands:
      - /ip dhcp-server print
  register: dhcp


- debug:
    var: dhcp.stdout_lines


- name: Verify DHCP Network
  community.routeros.command:
    commands:
      - /ip dhcp-server network print
  register: network


- debug:
    var: network.stdout_lines


- name: Verification done
  debug:
    msg: SUCCESS
